name: bevy_tmx

on:
  push:
    branches: [0.6]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: cargo build
        run: |
          cargo build